"""fix user model fields

Revision ID: 193590a2c807
Revises: 3b7c3137d8aa
Create Date: 2026-04-29 22:15:32.226094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '193590a2c807'
down_revision: Union[str, None] = '3b7c3137d8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_statuses',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mime_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('ratings')
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('comments_material_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'courses', ['name'])
    op.create_unique_constraint(None, 'courses', ['number'])
    op.drop_constraint(op.f('favorites_material_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('likes_material_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    op.add_column('materials', sa.Column('mime_type_id', sa.SmallInteger(), nullable=False, server_default='1'))
    op.add_column('materials', sa.Column('status_id', sa.SmallInteger(), nullable=False, server_default='1'))
    op.alter_column('materials', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('materials', 'material_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materials', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materials', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materials', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('materials', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('materials_subject_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_course_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_material_type_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_author_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_program_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'material_types', ['material_type_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'programs', ['program_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'mime_types', ['mime_type_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'material_statuses', ['status_id'], ['id'])
    op.drop_column('materials', 'status')
    op.drop_column('materials', 'mime_type')
    op.alter_column('programs', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('programs', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'programs', ['name'])
    op.create_unique_constraint(None, 'programs', ['code'])
    op.drop_constraint(op.f('subject_programs_program_id_fkey'), 'subject_programs', type_='foreignkey')
    op.drop_constraint(op.f('subject_programs_course_id_fkey'), 'subject_programs', type_='foreignkey')
    op.drop_constraint(op.f('subject_programs_subject_id_fkey'), 'subject_programs', type_='foreignkey')
    op.create_foreign_key(None, 'subject_programs', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'subject_programs', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'subject_programs', 'programs', ['program_id'], ['id'])
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('subjects', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.SmallInteger(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'group_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('users_program_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_course_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'programs', ['program_id'], ['id'])
    op.create_foreign_key(None, 'users', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', postgresql.ENUM('STUDENT', 'MODERATOR', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_course_id_fkey'), 'users', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_program_id_fkey'), 'users', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'group_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.alter_column('subjects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('subjects', 'is_active')
    op.drop_constraint(None, 'subject_programs', type_='foreignkey')
    op.drop_constraint(None, 'subject_programs', type_='foreignkey')
    op.drop_constraint(None, 'subject_programs', type_='foreignkey')
    op.create_foreign_key(op.f('subject_programs_subject_id_fkey'), 'subject_programs', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subject_programs_course_id_fkey'), 'subject_programs', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subject_programs_program_id_fkey'), 'subject_programs', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'programs', type_='unique')
    op.drop_constraint(None, 'programs', type_='unique')
    op.alter_column('programs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('programs', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('materials', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='materialstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_program_id_fkey'), 'materials', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('materials_author_id_fkey'), 'materials', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('materials_material_type_id_fkey'), 'materials', 'material_types', ['material_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('materials_course_id_fkey'), 'materials', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('materials_subject_id_fkey'), 'materials', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materials', 'file_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('materials', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materials', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materials', 'material_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materials', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('materials', 'status_id')
    op.drop_column('materials', 'mime_type_id')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('likes_material_id_fkey'), 'likes', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('favorites_material_id_fkey'), 'favorites', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_material_id_fkey'), 'comments', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.drop_column('comments', 'is_deleted')
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('ratings_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ratings_pkey')),
    sa.UniqueConstraint('user_id', 'material_id', name=op.f('uq_user_material_rating'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('roles')
    op.drop_table('mime_types')
    op.drop_table('material_statuses')
    # ### end Alembic commands ###
